[project]
name = "storybook"
version = "0.1.0"
description = "Turn text narratios into multi-image visual stories"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "transformers",
]
